// RESTO DEUNA DIVISIÓN : PARTICULARMENTE OPERACION ESTA SIRVE APRA SABER SI UN NUMERO ES PAR O IMPAR

var resto = 15 % 5;

console.log(resto);

resto = 15 % 2;

console.log(resto);

//:::::::::::::::: ejemplo aplicativo del resto::::::::::::::


var  litrosDeJugo = 8;

var personas = 3;

// ¿cuánto de jugo sobrara si se le quiere dar cantidades de litros enteras a cada uno?

var operacionResto = litrosDeJugo % personas;

console.log(operacionResto);
