// Notación de corchetes: Accediendo a los caracteres

var lenguajeDeProgramacion ="JavaScript";

console.log(lenguajeDeProgramacion[0]);
console.log(lenguajeDeProgramacion[1]);
console.log(lenguajeDeProgramacion[2]);
console.log(lenguajeDeProgramacion[3]);
console.log(lenguajeDeProgramacion[4]);
console.log(lenguajeDeProgramacion[5]);
console.log(lenguajeDeProgramacion[6]);
console.log(lenguajeDeProgramacion[7]);
console.log(lenguajeDeProgramacion[8]);
console.log(lenguajeDeProgramacion[9]);

