// Arreglos anidados: los arreglos pueden contener cualquier tipo de datos
//                    incluyendo otros arreglos.


//Ejmplo 01: Nota de estudiantes
var listaDeEstudiantes = [["Fritz" , 18] , ["Juan" , 15]];
console.log(listaDeEstudiantes);

// Ejemplo 02: Lista de produstos

var listaDeProductos = [["Camisa" , 20 , "cd123" ] , ["Pantalon" , 70 , "cd542"] , ["Zapatilla" , 220 , "cdz854"]];
console.log(listaDeProductos);



