// LISTA DE COMPRAS

var miListaDeComprras =[
    
    ["cereal", 3],
    ["galletas", 4],
    ["pan", 5],
    ["refresco", 7],
    ["poññp", 7],

];

console.log("Voy a compar " + miListaDeComprras[0][1] + " unidades de " + miListaDeComprras[0][0] +".");
console.log("Voy a compar " + miListaDeComprras[1][1] + " unidades de " + miListaDeComprras[1][0] +".");
console.log("Voy a compar " + miListaDeComprras[2][1] + " unidades de " + miListaDeComprras[2][0] +".");
console.log("Voy a compar " + miListaDeComprras[3][1] + " unidades de " + miListaDeComprras[3][0] +".");
console.log("Voy a compar " + miListaDeComprras[4][1] + " unidades de " + miListaDeComprras[4][0] +".");