// Sentencias Condicionales

/* 

if ( esta condicion es verdadera){
  hacemos las instrucciones
  que estan dentro de este programa
}

*/

// Ejemplo 01

if (true){
    console.log("La condición es verdadera")
}

// Ejemplo 02

var x = 5;

if(x > 2){
    console.log("x es un valor mayor y la ondición es verdadera")
}

// Ejemplo 03

var y = 5;

if ( y > 2 && y < 10){
    console.log("la condición es verdadera")
}


// Ejemplo 04

var estacion = "Invierno";

if (estacion == "Invierno"){
    console.log("Si, me gusta el invierno")
}

console.log( "si es falsa la condicipon sale estemensaje despues del condicional.")
