// Sentencias Condicionales

/* 

if ( esta condicion es verdadera){
  hacemos las instrucciones
  que estan dentro de este programa
}

*/

// Ejemplo 01

var x = 5;

if (x > 2){
    console.log("La condición es verdadera")
} else {
    console.log("La condición es falsa");
}



// ejemplo 2

var estacion = "Invierno";

if (estacion ==="Verano"){
    console.log("Comenzo el verano. Ya podemos ir a la playa");
} else {
    console.log("Ya quiero que llegue el verano para poder ir a la playa");
}

