
//67-crear-objetos

// Un obseto  en js biene a estar dada por una variable definida por let o var
// a la cual mdiante le signo = se le asigna  un conjunto de propiedades y valores 
// separados por una coma a excepcion del ultimo. Este conjunto de propiedades y valores estan
// dentro de unas { } segida de un punto y coma.

var miPerro = {
    "nombre": "Gino",
    "edad": 5,
    "peso" : 6,
    "raza" : "beagle"
};


// nota: las propiedades peuden ser string u números

var miObjeto = {
    5 : "cinco",
    6 :"seis"
}

